name: Rollback

on:
  workflow_dispatch:
    inputs:
      commit-to-rollback:
        required: false
        description: 'SHA-1 del commit para el rollback'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN }}

      - name: onDemand Rollback
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.commit-to-rollback != ''
        env:
          BRANCH_NAME: ${{ github.ref }}
          COMMIT: ${{ github.event.inputs.commit-to-rollback }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        shell: bash
        run: |
          BRANCH_NAME=${BRANCH_NAME#refs/heads/}
          echo "Rollback al SHA-1: $COMMIT de la rama $BRANCH_NAME"

          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          if [ "$(git rev-parse --is-shallow-repository)" = "true" ]; then
            git fetch origin $BRANCH_NAME --unshallow >/dev/null 2>&1
          else
            git fetch origin $BRANCH_NAME >/dev/null 2>&1
          fi

          # Asegurándose que el commit esté en la historia de la rama actual
          if git merge-base --is-ancestor $COMMIT origin/$BRANCH_NAME; then
            echo "El SHA-1 $COMMIT es parte del historial de la rama $BRANCH_NAME."

            # Reiniciando la rama para que el HEAD sea el commit deseado
            git checkout $BRANCH_NAME
            ROLLBACK_BRANCH="rollback/$BRANCH_NAME-$COMMIT"
            git checkout -b $ROLLBACK_BRANCH
            git add .
            git commit --allow-empty -m "Rollback commit $COMMIT"
            git push origin -u $ROLLBACK_BRANCH

            git checkout $BRANCH_NAME
            git reset --hard $COMMIT   
            git push origin $BRANCH_NAME --force

          else
            echo "El SHA-1 $COMMIT NO es parte del historial de la rama $BRANCH_NAME."
            exit 1
          fi
